:sparkles: (custom logger) add option to supply custom logger
botblock/BLAPI pull request #72
Opened 2021-04-02 16:08 UTC by MeerBiene

Closes #71

2021-04-02 21:36 UTC, T0TProduction requested changes
I like the setup in general, but specifically the typing left me with some questions as can be seen in the comments.

edit:
oh and also, why does this PR change the package-lock and yarn-lock? Did we have outdated lockfiles in the past commit?

2021-04-02 21:36 UTC, T0TProduction commented on src/blapi.ts
> +let userLogger: { info: (arg0: string) => void; warn: (arg0: string) => void; error: (arg0: any) => void; };
how about we save this type as a type? we could then use it later on where I mention using a type.

2021-04-02 21:36 UTC, T0TProduction commented on src/blapi.ts
> +export function setLogging(logOptions: boolean | { extended?: boolean, logger?: any }): void {
the parameter `logger` should definitely use the type of the logger here, to make it more convenient for typescript users to use (instead of waiting for the runtime error to be thrown later if something is wrong)

2021-04-02 21:36 UTC, T0TProduction commented on src/blapi.ts
> +  if (typeof logOptions === 'boolean' && logOptions === true) extendedLogging = true;
do we also want to support turning off extended logging? I don't really have a use case in mind where one would turn it on, and later off, but in the current version it would work, so removing that could be considered a breaking change. Same later on when called from within the object.

2021-04-02 21:36 UTC, T0TProduction commented on src/bttps.ts
> +  logger: any,
IMO this should definitely be typed
can we use the type from blapi.ts here, or would that break "normal" js? I remember having some issues with non-typescript bots when importing types from outside, but I think the issue there was that the file that had the types didn't export any functionality and therefore was completely ignored by JS, which then threw import errors for the types.

2021-04-02 21:36 UTC, T0TProduction commented on src/bttps.ts
> +      logger.info(' data:', await response.text());
pretty sure the type currently used for the logger does **not** support this syntax. Either we adjust the type, or we combine the parameters here to a single string *before* supplying them to the logger.

2021-04-03 07:21 UTC, MeerBiene commented
> I like the setup in general, but specifically the typing left me with some questions as can be seen in the comments.
> 
> edit:
> oh and also, why does this PR change the package-lock and yarn-lock? Did we have outdated lockfiles in the past commit?

Oh boi here we go again, tbh I didn't realize they changed, I just hacked my changes in and pushed it. I have no idea why they changed tho

2021-04-03 07:22 UTC, MeerBiene commented on src/bttps.ts
> +      logger.info(' data:', await response.text());
oof that completely went over my head, i just did CTRL + F and replaced console.log .info and  .error

2021-04-03 07:24 UTC, MeerBiene commented on src/blapi.ts
> +export function setLogging(logOptions: boolean | { extended?: boolean, logger?: any }): void {
I agree with your comment above, gonna declare it properly so as you said ts users dont get the error @runtime

2021-04-07 16:08 UTC, T0TProduction requested changes
some more questions, but in general no huge issues, just some optimization/cleanup

2021-04-07 16:08 UTC, T0TProduction commented on src/blapi.ts
> +  error: (err: any) => (userLogger ? userLogger.error(err) : console.error(`[ERROR] BLAPI ${err}`)),
a question, do we want to include the `[WARN (etc.)] BLAPI` tag in the custom logger as well, or is there a reason we only add that part to console logs?

2021-04-07 16:08 UTC, T0TProduction commented on src/bttps.ts
> +
did importing here throw errors when using it in js?

2021-04-07 16:08 UTC, T0TProduction commented on src/bttps.ts
> +export async function get<T>(url: string, log: UserLogger): Promise<T> {
lets call this logger instead of log as well, jut for consistency?

2021-04-07 16:08 UTC, T0TProduction commented on src/blapi.ts
> +      posts.push(post(apiPath, apiKeys[listname], sendObj, extendedLogging, userLogger));
should the value passed as logger be `log` instead of userLogger here?

2021-04-07 16:08 UTC, T0TProduction commented on src/blapi.ts
> +let userLogger: UserLogger;
does this make typescript see that it could be undefined, or do we want/need to adjust they type to be `: UserLogger | undefined` ?

2021-04-07 18:51 UTC, MeerBiene commented on README.md
>  blapi.setLogging(true);
Probably marking it as deprecated is the best choice, especially with someone in mind that used the lib before and when they come back they are probably wondering.

2021-04-07 18:53 UTC, MeerBiene commented on src/blapi.ts
> +  error: (err: any) => (userLogger ? userLogger.error(err) : console.error(`[ERROR] BLAPI ${err}`)),
I left it out because I thought the log levels are already taking care of that for the enduser, what i forgot tho is the "BLAPI" which we should definitely append so users know where the messages came from.

2021-04-07 18:57 UTC, MeerBiene commented on src/bttps.ts
> +
Importing in js worked fine, just es-lint was shouting at me for 'Dependency cycle detected', should I just disable the rule?

2021-04-07 19:01 UTC, MeerBiene commented on src/blapi.ts
> +let userLogger: UserLogger;
You are absolutely right is should be `UserLogger | undefined`

2021-04-07 21:22 UTC, T0TProduction commented on src/bttps.ts
> +
ah i see, yeah maybe its cleaner to import it and disable eslint for that line - since its really not a dependency cycle that's happening

2021-04-08 07:09 UTC, T0TProduction commented on src/bttps.ts
> +
nevermind, I just realized there's an easier solution: keep the type definition in here, and export it to blapi.ts
that way we have the benefit of defining the type only once **and** having no cycle

2021-04-08 10:04 UTC, T0TProduction approved these changes

2021-04-08 10:47 UTC, merged